sudo: required
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.3.1
  - 2.2
  - 2.1
  - 2.0
env:
  - DOCKER_VERSION=17.03.2~ce-0~ubuntu-trusty
  - DOCKER_VERSION=17.06.2~ce-0~ubuntu
  - DOCKER_VERSION=17.09.1~ce-0~ubuntu
  - DOCKER_VERSION=17.12.1~ce-0~ubuntu
  - DOCKER_VERSION=18.03.1~ce-0~ubuntu
  - DOCKER_VERSION=18.06.3~ce~3-0~ubuntu
matrix:
  fast_finish: true
before_install:
 - docker --version
 - gem install bundler
before_script:
 - sudo ./script/install_docker.sh ${DOCKER_VERSION} ${DOCKER_CE}
 - uname -a
 - docker --version
 - docker info
